---
mainfont: Libertinus Serif
headingfont: Libertinus Serif
execute: 
  echo: true
  eval: true
format:
  pdf:
    geometry: margin=1in
    mainfont: Libertinus Serif
    sansfont: Libertinus Serif
---

\LARGE\textbf{PSTAT160A Stochastic Processes}\vspace{5pt}\newline
\Large\textbf{Section 6}\vspace{5pt} \newline
\normalsize\textbf{Authors:} \textit{Denisse Alejandra Escobar Parra, John Inston} \newline
\textbf{Date:} \textit{November 18, 2025}\newline
\hrule

## Problem 1 - Dobrow 4.3

Let $X \sim \text{Poisson}(\lambda)$ and $Y \sim\text{Poisson}(\mu)$.  Assume that $X$ and $Y$ are independent.  Use PGFs to find the distribution of $X+Y$.

## Problem 2 - Dobrow 4.4

If $X$ has a _Negative Binomial Distribution_ with parameters $r$ and $p$, then $X$ can be written as the sum of $r$ i.i.d. _Geometric_ random variables with parameter $p$.  Use this fact to find the PGF of $X$.  Then, use the PGF to find the mean and variance of the negative binomial distribution.

## Problem 3 - Dobrow 4.12

A branching process has offspring distribution $\alpha=\left( \frac{1}{4}, \frac{1}{4}, \frac{1}{2} \right)$.  Find the following:

1. $\mu$;
2. $G(s)$;
3. The extinction probability;
4. $G_{2}(s)$; and
5. $\mathbb{P}(Z_{2}=0)$.

## Problem 4 - Dobrow 4.18

Consider a branching process with offspring distribution 
$$
\alpha=(p^2,2p(1-p),(1-p)^2);~~0<p<1.
$$

The offspring distribution is binomial with parameters $2$ and $1-p$.  Find the extinction probability $\eta$.

## Problem 5 - Dobrow 4.30

`R:` Simulate the branching process in Problem 3 (Dobrow 4.12).  Use your simulation to estimate the extinction probability $e$.