---
mainfont: Libertinus Serif
headingfont: Libertinus Serif
format:
  pdf:
    geometry: margin=1in
---

\LARGE\textbf{PSTAT160A Stochastic Processes}\vspace{5pt}\newline
\Large\textbf{Section 1 - Solutions}\vspace{5pt} \newline
\normalsize\textbf{Authors:} \textit{John Inston, Denisse Alejandra Escobar Parra} \newline
\textbf{Date:} \textit{September 30, 2025}\newline
\hrule

## Problem 1 - Dobrow Q1.1 

For the following scenarios identify a stochastic process $\{ X_{t} \}_{t \in I}$ describing: (i) $X_{t}$ in context, (ii) state space, and (iii) index set.  State whether the state space and index set are discrete or continuous.

1. From day to day the weather in International Falls, Minnesota is either rain, clear or snow.

2. At the end of each year, a 4-year college student either advances in grade, repeats their grade, or drops out.

3. Seismologists record daily earthquake magnitudes in Chile.  The largest recorded earthquake in history was the Valdivia, Chile earthquake on May 22nd 1960, which had a magnitude of 9.5 on the Richter scale.

4. Data is kept on the circumferences of trees in an arboretum. The arboretum covers a two square-mile area.  *Assume that the data is for a single time point.* 

5. Starting Monday morning at 9 a.m., as students arrive to class, the teacher records student arrival times. The class has 30 students and lasts for 60 minutes.

6. A card player shuffles a standard deck of cards by the following method: the top card of the deck is placed somewhere in the deck at random. The player does this 100 times to mix up the deck.

### Solution

1. $X_{t}$ denotes the weather on day $t$; discrete state space $\mathcal{S}:=\left\{ \text{Rain}, \text{Clear}, \text{Snow} \right\}$; discrete index set $I:=\{ 0,1,2,\dots \}$.

2. $X_{t}$ denotes the student's status in year $t$; discrete state space \newline $\mathcal{S}:=\{ \text{Drop}, \text{Fresh}, \text{Sophmore}, \text{Junior}, \text{Senior}, \text{Graduate} \}$; discrete index set $I:=\{ 0,1,2,\dots \}$.

3. $X_{t}$ denotes the earthquake magnitude on day $t$; continuous state space $\mathcal{S}:=\mathbb{R}^+$, discrete index set $I:=\{ 0,1,2,\dots \}$.

4. $X_{i}$ denotes the circumference of trees in an arboretum, continuous state space $\mathcal{S}:=\mathbb{R}^+$, continuous index set $I:=[0,2]\times[0,2]$ denoting the coordinate location of the tree.

5. $X_{i}$ denotes the lateness of students from the start of class, continuous state space $\mathcal{S}:=[0,60]$, discrete index set $I:=\{1, \dots, 30\}$ denoting the student.

6. $X_{t}$ denotes the ordering of the deck of cards, discrete state space $\#\mathcal{S}=52!$, discrete index set $I:=\{0, 1,\dots, 100\}$ denoting number of shuffles.


## Problem 2 - Dobrow Q1.2

A regional insurance company insures homeowners against flood damage.  Half of their policyholders are in Florida, 30% in Louisiana, and 20% in Texas.  Company actuaries give the estimates in @tbl-tab1 for the probability that a policyholder will file a claim for flood damage over the next year.

1. Find the probability that a random policyholder will file a claim for flood damage next year.

2. A claim was filed.  Find the probability that the policyholder is from Texas.

: Probability of Claim for Flood Damage {#tbl-tab1}

| State                | Florida | Louisiana | Texas |
|:---------------------|:-------:|:---------:|:-----:|
| Probability of Claim | 0.03    | 0.015     | 0.02  |

### Solution

For clarity we define the following events: $C$ the policy holder makes a claim; $T$ the holder is from Texas, $L$ the holder is from Louisiana and $F$ policy is from Florida.  We assume that events $T,L,F$ are independent (policy holders can only be from one state) and we note that 
$$
\mathbb{P}(\Omega)=\mathbb{P}(T\cup L\cup F)=\mathbb{P}(T)+\mathbb{P}(L)+\mathbb{P}(F)=0.5+0.3+0.2=1.
$$

For (1) using independence we can compute the weighted average
$$
\begin{aligned}
\mathbb{P}(C) & =\mathbb{P}((C\cap F)\cup(C \cap L)\cup (C \cap T) \\
 & = \mathbb{P}(C\cap F) + \mathbb{P}(C \cap L) +\mathbb{P}(C\cap T)\\
 & = \mathbb{P}(C|F)\mathbb{P}(F)+\mathbb{P}(C|L)\mathbb{P}(L) + \mathbb{P}(C|T)\mathbb{P}(T)\\
 & =0.03(0.5)+0.015(0.3) + 0.02(0.2) \\
 & = 0.0235.
\end{aligned}
$$

For (2) we compute using Bayes rule
$$
\begin{aligned}
\mathbb{P}(T|C) & =\frac{\mathbb{P}(T \cap C)}{\mathbb{P}(C)} \\
 & =\frac{\mathbb{P}(C|T)\mathbb{P}(T)}{\mathbb{P}(C)} \\
 & =\frac{0.02(0.2)}{0.0235} \\
 & =0.170212766.
\end{aligned}
$$

## Problem 3 - Dobrow Q1.3

Let $B_{1}, \dots, B_{k}$ be a partition of the sample space.  For events $A$ and $C$, prove the law of total probability for conditional probability
$$
\mathbb{P}(A|C)=\sum_{i=1}^{k}\mathbb{P}(A|B_{i}\cap C)\mathbb{P}(B_{i}|C).
$$

### Solution

*PROOF:*
From the definition of conditional probability and noting that $C=\bigcup_{i}(B_{i}\cap C)$ through independence of the partition regions we can compute
$$
\begin{aligned}
\sum_{i=1}^{k}\mathbb{P}(A|B_{i}\cap C)\cdot \mathbb{P}(B_{i}|C) & =\sum_{i=1}^{k} \frac{\mathbb{P}(A\cap (B_{i}\cap C))}{\mathbb{P}(B_{i}\cap C)}\cdot \frac{\mathbb{P}(B_{i}\cap C)}{\mathbb{P}(C)} \\
 & =\sum_{i=1}^{k} \frac{\mathbb{P}(A \cap (B_{i}\cap C))}{\mathbb{P}(C)} \\
 & =\frac{\mathbb{P}\left( A \cap \bigcup _{i=1}^k(B_{i}\cap C) \right)}{\mathbb{P}(C)} \\
 & =\frac{\mathbb{P}(A \cap C)}{\mathbb{P}(C)} \\
 & =\mathbb{P}(A|C).
\end{aligned}
$$
$\square$

## Problem 4 - Dobrow Q1.4

(See Problem 2) Among all policyholders who live within five miles of the Atlantic Ocean, 75% live in Florida, 20% live in Louisiana, and 5% live in Texas.  For those who live close to the ocean the probabilities of filing a claim increase, as given in Table 2.

: Table: Probability of claim for those within five miles of Atlantic Coast.

| State                | Florida | Louisiana | Texas |
| -------------------- | ------- | --------- | ----- |
| Probability of Claim | 0.10    | 0.06      | 0.06  |

Assume that a policyholder lives within five miles of the Atlantic coast. Use the law of total probability for conditional probability in Exercise 1.3 to find the chance they will file a claim for flood damage next year.

### Solution

Using definitions from Problem 2 and further defining event $A$ holder lives within five miles of the Atlantic coast we apply the law of total probability for conditional probability to compute
$$
\begin{aligned}
\mathbb{P}(C|A)  & = \mathbb{P}(C|F\cap A)\mathbb{P}(F|A)+\mathbb{P}(C|L\cap A)\mathbb{P}(L|A)+\mathbb{P}(C|T\cap A)\mathbb{P}(T|A) \\
 & = 0.10(0.75) + 0.06(0.2) + 0.06(0.05) \\
 & = 0.09.
\end{aligned}
$$

## Problem 5 - Dobrow Q1.5

Two fair six-sided dice are rolled.  Let $X_{1}, X_{2}$ be the outcomes of the first and second die, respectively.  

1. Find the conditional distribution of $X_{2}$ given that $X_{1}+X_{2}=7$.
2. Find the conditional distribution of $X_{2}$ given that $X_{1}+X_{2}=8$.

### Solution

For (1) from the definition of conditional probability we compute
$$
\begin{aligned}
p_{X_{2}|X_{1}+X_{2}=7}(x)  & = \mathbb{P}(X_{2}=x|X_{1}+X_{2}=7) \\
 & =\frac{\mathbb{P}(X_{1}+X_{2}=7|X_{2}=x)\mathbb{P}(X_{2}=x)}{\mathbb{P}(X_{1}+X_{2}=7)}  \\
 & =\frac{\mathbb{P}(X_{1}=7-x)\mathbb{P}(X_{2}=x)}{\mathbb{P}(X_{1}+X_{2}=7)}   \\
 & = \begin{cases}
\frac{{\frac{1}{6}\cdot \frac{1}{6}}}{\frac{6}{36}} = \frac{1}{6} & \text{if }x \in \{ 1, \dots, 6 \}, \\
0 & \text{otherwise}.
\end{cases}
\end{aligned}
$$

For (2) again from the definition of conditional probability we have
$$
\begin{aligned}
p_{X_{2}|X_{1}+X_{2}=7}(x)  & =\frac{\mathbb{P}(X_{1}=8-x)\mathbb{P}(X_{2}=x)}{\mathbb{P}(X_{1}+X_{2}=8)}   \\
 & = \begin{cases}
 \frac{{\frac{1}{6}\cdot \frac{1}{6}}}{\frac{5}{36}}=\frac{1}{5} & \text{if } x \in \{ 2, \dots, 6 \}, \\
    0 & \text{otherwise}.
\end{cases}
\end{aligned}
$$
